### ISSUE TITLE
uniapp本地测试正常。但打包(H5)后 nginx运行报错 f is not a function 

### ISSUE THREAD

**Issue by cnfanhua** [TencentCloud/chat-uikit-uniapp#18]
vue版本：vue3 + vite 
node版本：v16.19.0
npm版本：8.19.3
HBuilder X：3.8.12

错误图如下：
![](https://cdn.jsdelivr.net/gh/cnfanhua/imgs/other/picGo/202310201608880.png)

**Comment by cnfanhua** [comment]
补充一下，跟TUIGlobal?.global?相关的（TUIGlobal?.global?.navigateTo）（TUIGlobal?.global?.reLaunch）等等 都会报 xx is not a function.
![](https://cdn.jsdelivr.net/gh/cnfanhua/imgs/other/picGo/202310240844732.png)

**Comment by l-outsider** [comment]
h5 打包不能开启 tree shaking。
如果必须开启 treeshaking，需要将所有 uni api 的调用该为 uni上的直接调用。例如:
```js
uni.showToast()
```

不能是
```
let global = uni;
global.showToast();
```
