### ISSUE TITLE
跟着教程没启动成功

### ISSUE THREAD

**Issue by Minnull** [TencentCloud/chat-uikit-uniapp#4]
1.npm i 执行提示

pm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v19.3.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v19.3.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v19.3.0', npm: '9.2.0' }
npm WARN EBADENGINE }

up to date, audited 1681 packages in 26s

133 packages are looking for funding
  run `npm fund` for details

39 vulnerabilities (1 moderate, 30 high, 8 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

2.
<img width="428" alt="截屏2022-12-31 下午9 50 21" src="https://user-images.githubusercontent.com/19608781/210138953-dc6c82ca-2f30-4400-92f0-cc14008b951b.png">

**Comment by Tencent-Alice** [comment]
hi   根据您的报错，检查下网络环境重试下，    技术问题 欢迎交流 Q2562367495 注明来意
