### ISSUE TITLE
切换语言之后，页面的语言没有同步

### ISSUE THREAD

**Issue by kkks2024** [TencentCloud/chat-uikit-uniapp#54]
![image](https://github.com/user-attachments/assets/06992221-7dd6-43aa-a02f-29b6ac3f510a)
在翻译语言菜单切换语言之后，会话tab和通讯录tab中语言没有改变

**Comment by l-outsider** [comment]
翻译语言是指文本消息翻译的目标语言，而不是界面UI的语言。

**Comment by l-outsider** [comment]
设置界面语言可参考[该文档](https://cloud.tencent.com/document/product/269/111803)

**Comment by kkks2024** [comment]
> 设置界面语言可参考[该文档](https://cloud.tencent.com/document/product/269/111803)

使用`TUITranslateService.changeLanguage` 或者 `TUITranslateService.useI18n` 之后UI的语言不会实时改变。

**Comment by l-outsider** [comment]
暂不支持实时改变，语言是在 UI 初始化时确定的。
